name: Build and Deploy HTML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor

      - name: Build HTML
        run: |
          asciidoctor -r asciidoctor-diagram documents/specification/OpenCRG_specification_1_2.adoc -o OpenCRG_specification_1_2.html

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: OpenCRG_specification_1_2.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
